### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by sangtran0897** [sangtran0897/GetCostLaptopFromWebsites#2]
test

**Comment by sangtran140897** [comment]
oka
![bkg-blu](https://user-images.githubusercontent.com/85019356/120095226-f9f31780-c14e-11eb-8209-b588bda90f4c.jpg)

**Comment by sangtran0897** [comment]
@sangtran140897

**Comment by sangtran140897** [comment]
> @sangtran140897

ok

**Comment by sangtran0897** [comment]
new
